-- data.sql

-- Insert user data with autogenerated id
-- INSERT INTO user (name, dob) VALUES
--                                  ('John Doe', '1990-01-15'),
--                                  ('Jane Smith', '1985-05-20'),
--                                  ('Alice Johnson', '1995-09-10');
